server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # /best-dental-clinic-istanbul/ prefix ile gelen istekler (proxy üzerinden)
    location /best-dental-clinic-istanbul/ {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ /best-dental-clinic-istanbul/index.html;
    }

    # Root erişim
    location / {
        try_files $uri $uri/ /index.html;
    }
}
